name: Automation
on:
    push:
        branches:
            - master
        workflow dispatch:
   jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            -name: Print Hello World
            run: echo "Hello World"

